In [2]:
import numpy as np

x = np.array([[1],[5],[-1],[2.5]])

np.where(x > 0,1,0)

array([[1],
       [1],
       [0],
       [1]])

In [ ]:
import torch.nn as nn
import torch
from Sigmoid import Sigmoid

s = Sigmoid()
x = s.forward(np.array([[1],[5],[-1],[2.5]]))
print(f'x[mine] = {x}')
t = torch.Tensor([[1],[5],[-1],[2.5]])
s = nn.Sigmoid()
x = s(t)
print(f'x[torch] = {x}')

x[mine] = [[0.73105858]
 [0.99330715]
 [0.26894142]
 [0.92414182]]
x[torch] = tensor([[0.7311],
        [0.9933],
        [0.2689],
        [0.9241]])


In [ ]:
from ReLU import ReLU

r = ReLU()
x = r.forward(np.array([[1],[5],[-1],[2.5]]))
x

array([[1. ],
       [5. ],
       [0. ],
       [2.5]])

In [1]:
x = [[[0,1,2]],[[0,3,4]]]
x[0]

[[0, 1, 2]]

In [3]:
import numpy as np

input = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Let's say the output matrix Y is:
Y = np.zeros((2, 2, 2))  # (output_height, output_width, num_filters)

# After computing feature_map for filter 0:
feature_map0 = np.array([
    [10, 20],
    [30, 40]
])

# For filter 1:
feature_map1 = np.array([
    [50, 60],
    [70, 80]
])

print(Y)
# Assigning to the output:
Y[:, :, 0] = feature_map0  # Assigns feature map 0 to the first filter output
Y[:, :, 1] = feature_map1  # Assigns feature map 1 to the second filter output

Y
# Resulting Y:
# [[[10, 50], [20, 60]],
#  [[30, 70], [40, 80]]]


[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


array([[[10., 50.],
        [20., 60.]],

       [[30., 70.],
        [40., 80.]]])